name: earthaccess-dev
channels:
- conda-forge
dependencies:
# This environment bootstraps poetry, the actual dev environment
# is installed and managed with poetry
- python=3.9
- jupyterlab=3
- xarray>=0.19
- ipyleaflet>=0.13
- h5netcdf>=0.11
- pip
- pip:
  - poetry
